services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  DadayAndry\RpmTwigBundle\Extension\RequestParamExtension:
    tags : ['twig.runtimeds']
    